# Generated by Django 6.0.1 on 2026-01-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_stream', models.CharField(max_length=200)),
                ('covered_skills', models.TextField()),
                ('career_inclination', models.CharField(max_length=200)),
                ('time_availability', models.CharField(max_length=100)),
                ('financial_constraint', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('estimated_salary', models.CharField(max_length=100)),
                ('growth_prospects', models.TextField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.userinput')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
